### ISSUE TITLE
Create an audio module based on OpenAL.

### ISSUE THREAD

**Issue by IAmNotHanni** [inexorgame/entity-component-system#105]
Implement an `AudioModule` build on top of OpenAL.

Use the OpenAL programming guide: https://www.openal.org/documentation/

**Comment by IAmNotHanni** [comment]
A good C++ Tutorial: https://ffainelli.github.io/openal-example/.

**Comment by IAmNotHanni** [comment]
The programming guide is really well done. I consider this to be the resource for best practises.

**Comment by IAmNotHanni** [comment]
Since OpenAL only deals with raw audio data (PCM), we will need additional libraries to load our desired formats like [Ogg](https://en.wikipedia.org/wiki/Ogg) or [FLAC](https://en.wikipedia.org/wiki/FLAC).

**Comment by IAmNotHanni** [comment]
I'm going to implement a function which loads a `WAVE` file without using [ALUT](http://distro.ibiblio.org/rootlinux/rootlinux-ports/more/freealut/freealut-1.1.0/doc/alut.html).

**Comment by Fohlen** [comment]
@IAmNotHanni this is going to be deprecated by #113 ? Can we close?

**Comment by IAmNotHanni** [comment]
This is out of the scope of the entity component system.
We will create a dedicated audio engine repo for this later.
